src/Entity/PricingPlan.php
<?php

namespace App\Entity;

use App\Repository\PricingPlanRepository;
use App\Repository\PricingPlanFeatureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PricingPlanRepository::class)]
class PricingPlan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\OneToMany(mappedBy: 'pricingPlan', cascade:['persist'], orphanRemoval:true,  targetEntity: PricingPlanBenefit::class) ]
    private Collection $benefit;

    #[ORM\ManyToMany(targetEntity: PricingPlanFeature::class)]
    private Collection $features;

    

    public function __construct()
    {
        $this->benefit = new ArrayCollection();
        $this->features = new ArrayCollection();
        $this->benefit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, PricingPlanBenefit>
     */
    public function getBenefit(): Collection
    {
        return $this->benefit;
    }

    public function addBenefit(PricingPlanBenefit $benefit): static
    {
        if (!$this->benefit->contains($benefit)) {
            $this->benefit->add($benefit);
            $benefit->setPricingPlan($this);
        }

        return $this;
    }

    public function removeBenefit(PricingPlanBenefit $benefit): static
    {
        if ($this->benefit->removeElement($benefit)) {
            // set the owning side to null (unless already changed)
            if ($benefit->getPricingPlan() === $this) {
                $benefit->setPricingPlan(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PricingPlanFeature>
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(PricingPlanFeature $feature): static
    {
        if (!$this->features->contains($feature)) {
            $this->features->add($feature);
        }

        return $this;
    }
    
    public function hasFeature(PricingPlanFeature $feature): bool
    {
        return $this->features->contains($feature);
    }

      

    public function removeFeature(PricingPlanFeature $feature): static
    {
        $this->features->removeElement($feature);

        return $this;
    }

    /**
     * @return Collection<int, PricingPlanBenefit>
     */
    public function getBenefits(): Collection
    {
        return $this->benefit;
    }
}

src/Controller/PricingController.php
<?php

namespace App\Controller;

use App\Repository\PricingPlanRepository;
use App\Repository\PricingPlanFeatureRepository;
use App\Entity\PricingPlan;
use App\Entity\PricingPlanFeature;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PricingController extends AbstractController
{
    private $pricingPlanRepository;
    private $pricingPlanFeatureRepository;
    
    // this construct function was updated to symfony 6
    // the use of the methos getDoctrine is now outdated
    //you cant use two construct functions inside the class 

    public function __construct(
        PricingPlanRepository $pricingPlanRepository,
        PricingPlanFeatureRepository $pricingPlanFeatureRepository
    ) {
        $this->pricingPlanRepository = $pricingPlanRepository;
        $this->pricingPlanFeatureRepository = $pricingPlanFeatureRepository;
    }
    
    
    

    #[Route('/pricing', name: 'pricing')]
    public function index(): Response
    {
        $pricingPlans = $this->pricingPlanRepository->findAll();
        $features = $this->pricingPlanFeatureRepository->findAll();
        
        return $this->render('pricing/index.html.twig', [
            'pricing_plans' => $pricingPlans,
            'features' => $features,
        ]);
    }
}

templates/pricing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PricingController!{% endblock %}

{% block body %}
<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for pricing_plan in pricing_plans %}
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ pricing_plan.name }}</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">${{ pricing_plan.price }}<small class="text-body-secondary fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              {% for benefit in pricing_plan.benefits %}
              <li>{{ benefit.name}}</li>
              {% endfor %}
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            {% for pricing_plan in pricing_plans %}
            <th style="width: 22%;">{{ pricing_plan.name }}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
         {% for feature in features %}
            <tr>
                <th scope="row" class="text-start">{{ feature.name }}</th>
                {% for pricing_plan in pricing_plans %}
                    {% if pricing_plan.hasFeature(feature) %}
                        <td><i class="bi bi-check"></i></td>
                    {% else %}
                        <td></td>
                    {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>

        {# <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><i class="bi bi-check-lg"></i></td>
            <td><i class="bi bi-check-lg"></i></td>
            <td><i class="bi bi-check-lg"></i></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><i class="bi bi-check-lg"></i></td>
            <td><i class="bi bi-check-lg"></i></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><i class="bi bi-check-lg"></i></td>
            <td><i class="bi bi-check-lg"></i></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><i class="bi bi-check-lg"></i></td>
          </tr>
        </tbody> #}
      </table>
    </div>
  </main>
{% endblock %}